package com.example.springboot;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;


@RestController// This means that this class is a Controller
// This means URL's start with /db (after Application path)
public class dbaddController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @RequestMapping(value="/dbadd", method=RequestMethod.POST)
    public String addNewUser (@ModelAttribute mysqlUser mysqlUser, Model model) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        model.addAttribute("my", mysqlUser);
        mysqlUser n = new  mysqlUser();
        // n.setId(1);
         n.setName(mysqlUser.getName());
         n.setEmail(mysqlUser.getEmail());
        userRepository.save(n);
        return "Saved";
    }
}