package com.example.springboot;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import java.util.ArrayList;
import java.util.*;

@RestController// This means that this class is a Controller
@RequestMapping(value="/db") // This means URL's start with /db (after Application path)
public class dbController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(value ="/dbget")
    public @ResponseBody List<mysqlUser> getAllUsers() {
        // This returns a list,by default return type is Iterable
        // Start dispplay use of Iterable
        List<mysqlUser> result = new ArrayList<mysqlUser>();
        Iterable<mysqlUser> iterable;
        iterable = userRepository.findAll();
        iterable.forEach(result::add);

        //End of dispplay use of Iterable
        return result;

       // return userRepository.findAll();
    }
}